repos:
    - repo: https://github.com/charliermarsh/ruff-pre-commit
      rev: v0.14.9
      hooks:
          - id: ruff
            args: [--fix, --exit-non-zero-on-fix]
    # - repo: https://github.com/pre-commit/mirrors-mypy
    #   rev: "v1.19.0" # Use the revision you want here
    #   hooks:
    #       - id: mypy
    # - repo: local
    #   hooks:
    #       - id: pytest
    #         name: pytest
    #         language: unsupported
    #         entry: pytest
ci:
    autofix_prs: true
    autoupdate_schedule: weekly
    submodules: false
